<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use Inertia\Inertia;
use Inertia\Response;

/**
 * Public Standard Operating Procedures section for dvaughnhouse.org.
 *
 * Source of truth is the markdown in resources/sops/*.md; the .html files
 * beside them are generated by resources/sops/build.sh and served as-is.
 */
class SopController extends Controller
{
    /**
     * Manifest of published SOP documents. Slug => metadata.
     * Only slugs listed here are routable (no path traversal).
     */
    private const DOCUMENTS = [
        'about' => [
            'file' => '00-about.html',
            'id' => 'ABOUT',
            'title' => 'About the Glenride SOPs',
            'status' => 'DRAFT v0.1',
            'owner' => 'Lead Director',
            'approver' => 'President',
            'description' => 'What these SOPs are, the best-practice basis behind them, and the document-control convention. Nothing here is binding until approved.',
        ],
        'sop-001-study-approval' => [
            'file' => 'SOP-001-study-approval.html',
            'id' => 'SOP-001',
            'title' => 'Study Approval',
            'status' => 'DRAFT v0.1',
            'owner' => 'Lead Director',
            'approver' => 'President',
            'description' => 'Every study enters through the same door: written proposal, reviewed, approved before a dollar is spent.',
        ],
        'sop-002-research-records' => [
            'file' => 'SOP-002-research-records.html',
            'id' => 'SOP-002',
            'title' => 'Research Records',
            'status' => 'DRAFT v0.1',
            'owner' => 'Department Director',
            'approver' => 'Lead Director',
            'description' => 'What counts as a research record, how it is kept, and the ALCOA-C integrity bar it must clear.',
        ],
        'sop-003-conflicts-of-interest' => [
            'file' => 'SOP-003-conflicts-of-interest.html',
            'id' => 'SOP-003',
            'title' => 'Conflicts of Interest',
            'status' => 'DRAFT v0.1',
            'owner' => 'Lead Director',
            'approver' => 'President',
            'description' => 'Disclosure, institutional review, and documented management plans for financial conflicts of interest.',
        ],
        'sop-004-study-budget-tracking' => [
            'file' => 'SOP-004-study-budget-tracking.html',
            'id' => 'SOP-004',
            'title' => 'Study Budget Tracking',
            'status' => 'DRAFT v0.1',
            'owner' => 'Lead Director (Treasury holds the ledger)',
            'approver' => 'President',
            'description' => 'How study spend is tracked against the approved budget across the five-stage budget cycle.',
        ],
        'sop-outline' => [
            'file' => 'sop-outline.html',
            'id' => 'OUTLINE',
            'title' => 'Full SOP Outline (23 SOPs)',
            'status' => 'Outline',
            'owner' => '—',
            'approver' => '—',
            'description' => 'The table of contents for the complete SOP library: 23 procedures across 7 groups. Each gets written one at a time.',
        ],
    ];

    /**
     * Display the SOP library index.
     */
    public function index(Request $request): Response
    {
        $documents = [];
        foreach (self::DOCUMENTS as $slug => $meta) {
            $documents[] = array_merge(['slug' => $slug], $meta);
            unset($documents[count($documents) - 1]['file']);
        }

        return Inertia::render('Sops/Index', [
            'documents' => $documents,
        ]);
    }

    /**
     * Display a single SOP document.
     */
    public function show(Request $request, string $slug): Response
    {
        if (! array_key_exists($slug, self::DOCUMENTS)) {
            abort(404, 'SOP document not found.');
        }

        $meta = self::DOCUMENTS[$slug];
        $path = resource_path('sops/' . $meta['file']);

        if (! File::exists($path)) {
            abort(404, 'SOP document not found.');
        }

        $document = array_merge(['slug' => $slug], $meta);
        unset($document['file']);
        $document['html'] = File::get($path);

        return Inertia::render('Sops/Show', [
            'document' => $document,
        ]);
    }
}
